site_name: superheroes-ws
site_description: RESTFul web services for super heroes management
repo_url: https://github.com/iwansyahp/superheroes-ws
site_dir: site
copyright: Copyright &copy; 2019, <a href="https://github.com/iwansyahp">iwansyahp</a>.
dev_addr: 0.0.0.0:8001

nav:
  - Home: 'index.md'
  - API:
    - Authentication: 'api/authentication.md'
    - Users: 'api/users.md'
